#!/bin/bash
#
# ©2018,2019,2020 Michael Neill Hartman
#

ETH_ADDRESS="0x45afaF2831E93293Edb718E3Ef8F64671900AF49"
POWERLIMIT_WATTS="110"
CORE_OVERCLOCK="50"
MEMORY_OVERCLOCK="600"
WORKER="1660ti"

IS_AMD=$(lspci | grep VGA | grep -i amd)
IS_NVIDIA=$(lspci | grep VGA | grep -i nvidia)

[[ ${IS_NVIDIA} != "" ]] && {
sudo nvidia-smi -pl $POWERLIMIT_WATTS
GPUS=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | tail -1)
NVD=nvidia-settings
sudo nvidia-smi -pm 1
gpu=0
while [[ $gpu -lt $GPUS ]]
do
${NVD} -a [gpu:$gpu]/GPUGraphicsClockOffset[2]=$CORE_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUMemoryTransferRateOffset[2]=$MEMORY_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUGraphicsClockOffset[3]=$CORE_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUMemoryTransferRateOffset[3]=$MEMORY_OVERCLOCK
gpu=$(($gpu+1))
done ## while [[ $gpu -lt $GPUS ]]
} ## [[ ${IS_NVIDIA} != "" ]] && {


[[ ${IS_AMD} != "" ]] && {
FAN_SPEED=50
CORE_OVERCLOCK_LEVEL=7
MEMORY_OVERCLOCK_LEVEL=1
FAN_SP=$(awk "BEGIN {printf \"%.0f\n\", 255 * $FAN_SPEED/100}")
sudo '/home/m1/rocm-smi' -s
sudo '/home/m1/rocm-smi' -r
sudo '/home/m1/rocm-smi' --setperflevel high
sudo '/home/m1/rocm-smi' --setmclk $MEMORY_OVERCLOCK_LEVEL
sudo '/home/m1/rocm-smi' --setsclk $CORE_OVERCLOCK_LEVEL
sudo '/home/m1/rocm-smi' --setfan $FAN_SP -f
} ## [[ ${IS_AMD} != "" ]] && {


SPACE_7="       "
echo "
${SPACE_7}GPUS is: $GPUS"

${SPACE_7}POWERLIMIT_WATTS is: $POWERLIMIT_WATTS"

${SPACE_7}CORE_OVERCLOCK is: $CORE_OVERCLOCK"

${SPACE_7}MEMORY_OVERCLOCK is: $MEMORY_OVERCLOCK"

${SPACE_7}ETH_ADDRESS is: $ETH_ADDRESS"

${SPACE_7}WORKER is: $WORKER"
"

cd /home/m1/1.18a

xterm -e ./lolMiner --algo ETHASH --pool us1.ethermine.org:4444 --user ${ETH_ADDRESS}.${WORKER}
