#!/bin/bash
#
# ©2018,2019,2020 Michael Neill Hartman
#

ETH_ADDRESS="0x45afaF2831E93293Edb718E3Ef8F64671900AF49"
POWERLIMIT_WATTS="115"
CORE_OVERCLOCK="50"
MEMORY_OVERCLOCK="1000"

WORKER="oros_local"
IS_AMD=$(lspci | grep VGA | grep -i amd)
IS_NVIDIA=$(lspci | grep VGA | grep -i nvidia)

[[ ${IS_NVIDIA} != "" ]] && {
[[ ${IS_AMD} == "" ]] && WORKER=$(lspci | grep VGA | grep -i nvidia | tr ' ' '_' | tr '[]' '\n' | head -2 | tail -1 | tr '_' ' ' | awk '{print $NF}')
sudo nvidia-smi -pl $POWERLIMIT_WATTS
GPUS=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | tail -1)
NVD=nvidia-settings
sudo nvidia-smi -pm 1
gpu=0
while [[ $gpu -lt $GPUS ]]
do
${NVD} -a [gpu:$gpu]/GPUGraphicsClockOffset[2]=$CORE_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUMemoryTransferRateOffset[2]=$MEMORY_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUGraphicsClockOffset[3]=$CORE_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUMemoryTransferRateOffset[3]=$MEMORY_OVERCLOCK
gpu=$(($gpu+1))
done ## while [[ $gpu -lt $GPUS ]]
} ## [[ ${IS_NVIDIA} != "" ]] && {

[[ ${IS_AMD} != "" ]] && {
[[ ${IS_NVIDIA} == "" ]] && WORKER=$(lspci | grep VGA | grep -i amd | tr ' ' '_' | tr '[]' '\n' | head -4 | tail -1 | tr '_' ' ' | awk '{print $(NF-1)}' | tr '/' ' ' | awk '{print $NF}')
FAN_SPEED=25
CORE_OVERCLOCK_LEVEL=2
MEMORY_OVERCLOCK_LEVEL=3
FAN_SP=$(awk "BEGIN {printf \"%.0f\n\", 255 * $FAN_SPEED/100}")
cd /home/oros/rocm-smi
sudo ./rocm-smi -s
sudo ./rocm-smi -r
sudo ./rocm-smi --setperflevel high
sudo ./rocm-smi --setmclk $MEMORY_OVERCLOCK_LEVEL
sudo ./rocm-smi --setsclk $CORE_OVERCLOCK_LEVEL
sudo ./rocm-smi --setfan $FAN_SP -f
} ## [[ ${IS_AMD} != "" ]] && {

SPACE_7="     "
echo "
${SPACE_7}oros local

${SPACE_7}AMD GPUS: $IS_AMD

${SPACE_7}NVIDIA GPUS: $IS_NVIDIA

${SPACE_7}POWERLIMIT_WATTS is: $POWERLIMIT_WATTS

${SPACE_7}CORE_OVERCLOCK is: $CORE_OVERCLOCK

${SPACE_7}MEMORY_OVERCLOCK is: $MEMORY_OVERCLOCK

${SPACE_7}ETH_ADDRESS is: $ETH_ADDRESS

${SPACE_7}WORKER is: $WORKER
"

cd /home/oros/1.19

xterm -e ./lolMiner --algo ETHASH --pool us1.ethermine.org:4444 --user ${ETH_ADDRESS}.${WORKER}

exec true
#!/bin/bash

cd ~; rm -rf Desktop Documents Downloads Music Pictures Public Templates Videos

sudo apt install xterm -y





sudo apt install ocl-icd-opencl-dev -y


sudo ./amdgpu-install --headless --no-dkms -y


sudo ./amdgpu-install --opencl=legacy,pal --headless --no-dkms -y



sudo ./amdgpu-pro-install --opencl=legacy,pal --headless -y




sudo ./amdgpu-pro-install --opencl=legacy,pal --headless --no-dkms -y


sudo ./amdgpu-pro-install --uninstall



sudo apt install binutils -y





sudo bash kytulendu 



sudo ./amdgpu-install --no-dkms -y


sudo ./amdgpu-pro-install -y


sudo ./amdgpu-install --uninstall -y



