#!/bin/bash

cd /var/log

> /var/log/auth.log

> /var/log/dpkg.log

> /var/log/syslog

> /var/log/Xorg.0.log

> /var/log/kern.log

> ~/.bash_history

> ~/.bashrc

rm -rf ~/.compiz

[[ -e ~/.ICEauthority ]] && rm ~/.ICEauthority

rm -rf ~/.local

rm -rf ~/.mozilla

echo "done"
